name: "Articho Deployment"
description: "This action make a deployment with github actions to the implied apps from articho."
author: "Ibrael Espinosa"
inputs:
  github_token:
    required: true
    description: The github token to send deployments to the api
  now_token:
    description: "zeit.co token"
    required: true

  firebase_token:
    description: "firebase token"
    required: true

  firebase_project:
    description: firebase project
    required: true

  app:
    description: "The package app to deploy"
    required: true

  app_name:
    description: "The application name in now.sh"
    required: true

  prod:
    description: "Is production deployment"
    required: false
    default: false

  alias:
    description: "The alias for this deployment"
    required: false

  debug:
    description: Debug the output to check the errors
    required: false
    default: false

outputs:
  environment-url:
    description: "deployment preview URL"

  log-url:
    description: "Logs url"

  deployment-id:
    description: "Deployment ID"

  app:
    description: the app throwing this deployment

  payload:
    description: last payload with all data from deployment

runs:
  using: node12
  main: "dist/index.js"

branding:
  icon: "check"
  color: "black"
